name: 1.0.$(Rev:r)
trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: '35174a8f-edaa-4891-891d-f017c5338f2c'
  imageRepository: 'demo/subscriber-api'
  dockerfilePath: '$(Build.SourcesDirectory)/Services/Demo.Subscriber.API/Dockerfile'
  tag: '$(Build.BuildNumber)'

steps:

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: $(tag)
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'Infrastructure'
    artifact: 'Infrastructure'
    publishLocation: 'pipeline'
